# Generated by Django 5.1.4 on 2025-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('technical', 'فنی'), ('services', 'خدمات'), ('other', 'سایر')], max_length=20, null=True, verbose_name='بخش فعالیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('hourly', 'ساعتی'), ('contract', 'قراردادی')], max_length=20, null=True, verbose_name='نوع استخدام'),
        ),
    ]
