# Generated by Django 5.1.4 on 2024-12-17 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, verbose_name='کد پرسنلی')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('event_type', models.CharField(max_length=10, verbose_name='نوع رویداد')),
                ('device_id', models.CharField(max_length=10, verbose_name='شناسه دستگاه')),
                ('status', models.CharField(max_length=10, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ ورود و خروج',
                'verbose_name_plural': 'لاگ\u200cهای ورود و خروج',
                'constraints': [models.UniqueConstraint(fields=('personnel_code', 'time', 'date'), name='unique_attendance_log')],
            },
        ),
    ]
