# Generated by Django 5.1.4 on 2025-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_alter_worklog_device_id_alter_worklog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
